spring:
  application:
    name: sub-problem
  #datasource
  datasource:
    url: jdbc:mysql://{your-rds-url}/sw?serverTimezone=UTC
    #url: jdbc:mysql://localhost/sw?serverTimezone=UTC
    username: {id}
    password: {password}
    #driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
  #JPA
  jpa:
    hibernate:
      ddl-auto: create-drop
    #show-sql: true #this is the simplest way to dump the queries
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true #jpa.properties.hibernate.format_sql = true <- th beautify or pretty print hte SQL

#Fegin
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true
    command:
      default:
        execution:
          isolation:
            strategy: THREAD
#server
server:
  port:
    8078

---
spring:
  profiles:
    active: debug
  datasource:
    url: jdbc:mysql://localhost/sw?serverTimezone=UTC
    username: root
    password: tkdals12
    #driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
#Eureka
eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-seconds: 30
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
    instance-id: ${spring.application.name}:${server.port}
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8081/eureka/
      preferSameZoneEureka: true
---
spring:
  profiles: ap-northeast-2a

  datasource:
    url: jdbc:mysql://{your-rds-url}/sw?serverTimezone=UTC
    username: root
    password: tkdals12
    #driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
eureka:
  instance:
    lease-renewal-interval-in-seconds: 30
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    metadata-map:
        instanceId: ${spring.application.name}:${server.port}
        zone: ap-northeast-2a
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    region: ap-northeast-2
    service-url:
      ap-northeast-2a:  http://{eureka-url-2a-url}:8081/eureka
      ap-northeast-2c:  http://{eureke-regions-2c-url}:8082/eureka
      defaultZone: http://{eureka-url-2a-url}:8081/eureka, http://{eureke-regions-2c-url}:8082/eureka
    availability-zones:
      ap-northeast-2: ap-northeast-2a, ap-northeast-2c
    prefer-same-zone-eureka: false
---
spring:
  profiles: ap-northeast-2c
  datasource:
    url: jdbc:mysql://{your-rds-url}/sw?serverTimezone=UTC
    username: root
    password: tkdals12
    #driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximum-pool-size: 10
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}:${random.value}
    metadata-map:
      instanceId: ${spring.application.name}:${server.port}
      zone: ap-northeast-2c
  client:
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    region: ap-northeast-2
    service-url:
      ap-northeast-2a:  http://{eureka-url-2a-url}:8081/eureka
      ap-northeast-2c:  http://{eureke-regions-2c-url}:8082/eureka
      defaultZone: http://{eureka-url-2a-url}:8081/eureka, http://{eureke-regions-2c-url}:8082/eureka
    availability-zones:
      ap-northeast-2: ap-northeast-2a, ap-northeast-2c
    prefer-same-zone-eureka: false

